---
- name: Create {{ roon_server_path }}
  file:
    path: "{{ roon_server_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0775
  become: true

- name: Create {{ roon_server_path }}/data
  file:
    path: "{{ roon_server_path }}/data"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0775
  become: true

- name: Create {{ roon_server_music_path }}
  file:
    path: "{{ roon_server_music_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0775
  become: true
