---
- name: Docker pull latest elgeeko/roon-server
  community.general.docker_image:
    name: elgeeko/roon-server:latest
    source: pull
    force_source: true
  register: dockerimage

- name: Configure Docker network {{ roon_network_macvlan.name }}
  community.general.docker_network:
    name: "{{ roon_network_macvlan.name }}"
    state: "{{ (roon_network_mode == 'macvlan') | ternary('present', 'absent') }}"
    driver: macvlan
    driver_options:
      macvlan_mode: private
      parent: "{{ roon_network_macvlan.interface }}"
    ipam_config:
      - subnet:  "{{ roon_network_macvlan.subnet }}"
        gateway: "{{ roon_network_macvlan.gateway }}"
  register: dockernetwork

- name: Get group ID for audio
  ansible.builtin.getent:
    database: group
    key: audio

- name: Start roon-server docker container
  community.general.docker_container:
    name: roon-server
    image: elgeeko/roon-server:latest
    state: started
    recreate: "{{ dockerimage.changed or dockernetwork.changed }}"
    restart_policy: unless-stopped
    cleanup: true
    keep_volumes: false
    hostname: "{{ roon_server_name }}"
    publish_all_ports: true
    privileged: "{{ roon_container_privileged }}"
    groups:
      - "{{ getent_group.audio[1] }}"
    volumes:
      - "{{ roon_server_path }}/data:/var/roon"
      - "{{ roon_server_music_path }}:/music:ro"
      - /run/udev:/run/udev:ro # allow querying USB information
      - /usr/share/alsa:/usr/share/alsa # ALSA audio
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    devices:
      - /dev/bus/usb
      - /dev/snd
    # attach to macvlan network in macvlan mode, otherwise leave empty
    networks: "{{ (roon_network_mode == 'macvlan') \
      | ternary( \
        [{'name': roon_network_macvlan.name, \
          'ipv4_address': roon_network_macvlan.ipv4_address}], \
        [] ) }}"
    network_mode: "{{ roon_network_mode }}"
    networks_cli_compatible: false
    purge_networks: "{{ roon_network_mode == 'macvlan' }}"
