---
- name: Create samba directory {{ roon_samba_path }}
  ansible.builtin.file:
    path: "{{ roon_samba_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode:  0775
  become: true

- name: Create samba user
  ansible.builtin.user:
    name: "{{ roon_samba_media_user.name }}"
    password: "!" # disabled
    shell: /sbin/nologin
    create_home: false
  become: true
  register: user

- name: Record uid and gid for samba user
  ansible.builtin.set_fact:
    roon_samba_media_user: "{{ roon_samba_media_user | combine({ \
      'uid': user.uid, \
      'gid': user.group \
     }) }}"

- name: Deploy samba user file
  ansible.builtin.template:
    src: smb-users.j2
    dest: "{{ roon_samba_path }}/smb-users"
  notify: roon_samba_restart_required

- name: Deploy samba configuration smb.conf
  ansible.builtin.template:
    src:  smb.conf.j2
    dest: "{{ roon_samba_path }}/smb.conf"
  notify: roon_samba_restart_required

- name: Docker pull latest elgeeko/samba:{{ samba_docker_tag }}
  community.general.docker_image:
    name: elgeeko/samba:{{ samba_docker_tag }}
    source: pull
    force_source: true
  notify: roon_samba_restart_required

- name: Flush handlers to set variable roon_samba_restart_required
  ansible.builtin.meta: flush_handlers

- name: Start samba docker container
  community.general.docker_container:
    name: samba
    image: elgeeko/samba:{{ samba_docker_tag }}
    state: started
    recreate: "{{ roon_samba_restart_required }}"
    restart_policy: unless-stopped
    cleanup: true
    keep_volumes: false
    hostname: "{{ roon_hostname }}"
    network_mode: host
    # ports:
    #   - 137:137/udp # netbios name service (WINS)
    #   - 138:138/udp # netbios datagram service
    #   - 139:139/tcp # netbios session service
    #   - 445:445/tcp # samba via TCP
    volumes:
      - roon-server-cache:/opt/samba/shares/roon_backup:ro
      - "{{ roon_server_music_path }}:/opt/samba/shares/music"
      - "{{ roon_samba_path }}/smb-users:/opt/samba/smb-users:ro"
      - "{{ roon_samba_path }}/smb.conf:/etc/samba/smb.conf:ro"
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
